import System.IO  
import System.IO.Error
import Control.Exception as E
import System.Environment
import System.Random
import System.Exit

main = do 
    return 1
    exitWith $ ExitFailure 5
